### ISSUE TITLE
F&C Apprentice/Developer/MasterBuilder journey

### ISSUE THREAD

**Issue by iteles** [foundersandcoders/playbook#2]
The journey in [this hackpad](https://hackpad.com/Developer-journey-at-FAC-fuiaA53DPlh) needs to be formalised and added to the playbook :+1:

**Comment by olizilla** [comment]
Perhaps not the best place to put this endorsement, but, GOOD JOB. The plan listed in the hackpad is a good one :+1:

**Comment by iteles** [comment]
Thanks @olizilla! @sofer @FilWisher @nelsonic and I welcome any improvements of course :wink:

**Comment by iteles** [comment]
@sofer Offered to start putting this together in the [April 22nd Curriculum Development meeting](https://hackpad.com/FAC5-Curriculum-FHdlXg3qBKm) (will also add a link to this in the FAC5 gitbook)

**Comment by sofer** [comment]
@iteles I have taken and tidied up the copy from the hackpad.

https://github.com/foundersandcoders/playbook/blob/master/journey.md

And @olizilla thank you for your kind words.

**Comment by iteles** [comment]
PR #7 , #10 &  #11 :+1:
