### ISSUE TITLE
foundation.md needs updating

### ISSUE THREAD

**Issue by iteles** [foundersandcoders/playbook#25]
Worth updating [foundation.md](https://github.com/foundersandcoders/playbook/blob/master/foundation.md) with what we've done this time around so we have a decent reference for next time!
@sofer Assigning to you as I've been out of the office quite a bit these last couple of weeks

**Comment by sofer** [comment]
@iteles we are working on this. It'll definitely be updated once we know what we are updating it with.

**Comment by sofer** [comment]
@iteles updated to what we now plan to do.

**Comment by iteles** [comment]
@sofer Who's in charge of week 1?
