### ISSUE TITLE
F&C blogging section?

### ISSUE THREAD

**Issue by iteles** [foundersandcoders/playbook#3]
Do we want a section on the kinds of blog posts we're always looking for people to read (and a note of who is accountable for the blog - currently @sofer)?

**Comment by sofer** [comment]
@iteles we probably want tutorials and client interviews. On Hugh's suggestion, I am going to put together a template for interview questions and start sending them out to MVP cients.

**Comment by sofer** [comment]
@iteles this is still in my inbox, but I don't think it's enough to just write blog posts, we need to decide what the message is that we want to put across. More posts saying what a transformative experience the course is ("it changed my life!"), however lovely they are for us to read, are in danger of getting repetitive. Right now, we are probably more interested in case studies and tutorials.

**Comment by iteles** [comment]
@sofer Agreed. We have so much going on that we need to decide how much of a priority the blog is as well.  
We should certainly have a section on it in the playbook when we decide what the content and editorial calendar should be. Maybe we need an `awaiting prioritisation` label or something of the sort.

**Comment by iteles** [comment]
@sofer Is this just a case of 'we're no longer blogging and will look into it if we start doing so again'?

**Comment by sofer** [comment]
@iteles sorry, I wasn't even paying attention to which repo this was in. I didn't look at the top of the page and assumed it was a hangover from the old website.

But this fits into a wider question which we still haven't answered, so by all means re-open, but please assign to somebody else!
